### ISSUE TITLE
🥶 gap 3.0 FREEZ build nuxtjs

### ISSUE THREAD

**Issue by thisVioletHydra** [csstools/postcss-gap-properties#6]
![image](https://user-images.githubusercontent.com/11839238/133936277-1c59c021-60e3-4da9-918c-f6fa07a5eb2a.png)
if i unroll back -> 2.0
all work

p.s dev mod freez to

**Comment by jonathantneal** [comment]
There would need to be more details to help you resolve this. I’ve just looked over the plugin, and I cannot see any areas where this would create an infinite recursion. Please provide a replication. 🥺

**Comment by thisVioletHydra** [comment]
> There would need to be more details to help you resolve this. I’ve just looked over the plugin, and I cannot see any areas where this would create an infinite recursion. Please provide a replication. 🥺

https://codesandbox.io/s/zealous-herschel-lnqdz?file=/components/Tutorial.vue

all postcss plugins in: "postcss.libs.ts"

**Comment by thisVioletHydra** [comment]
webpack tries to complete the task and gets stuck!
![image](https://user-images.githubusercontent.com/11839238/134661573-7309f7fa-fc91-42d3-b535-a3b1d1d71bfb.png)
![image](https://user-images.githubusercontent.com/11839238/134661625-40dc5cf6-8754-4f57-9da5-e8055ffd7f33.png)

**Comment by thisVioletHydra** [comment]
@jonathantneal any news?

**Comment by Antonio-Laguna** [comment]
@thisVioletHydra do you have this isolated on any repo? I'd be happy to look into this but I don't see any stack traces or anything that could put me in the right place.

**Comment by thisVioletHydra** [comment]
> @thisVioletHydra do you have this isolated on any repo? I'd be happy to look into this but I don't see any stack traces or anything that could put me in the right place.

https://github.com/csstools/postcss-gap-properties/issues/6#issuecomment-926525505

![image](https://user-images.githubusercontent.com/11839238/143866185-411d25d1-d6a7-4fb8-b6df-54c2e3277994.png)

**Comment by romainmenke** [comment]
@thisVioletHydra this repo has move to [@csstools/postcss-plugins](https://github.com/csstools/postcss-plugins)

Would it be possible to create a repository on github with a minimal reproduction and [open a new issue here with a link](https://github.com/csstools/postcss-plugins/issues/new/choose)

- only the code required to trigger the issue.
- only the dependencies required to trigger the issue.

At the moment this is hard for us to track down because `postcss-gap-properties` on it's own can't cause infinite loops. (interop issue with another package / unexpected css source code)

_Personally I also try to avoid downloading things from unknown sources.
Having a github repo with a reproduction makes it easy to pull and run this in a headless VM._

**Comment by thisVioletHydra** [comment]
okay thx

**Comment by Antonio-Laguna** [comment]
@thisVioletHydra please read the above message, try to use last versions and, otherwise, report into the new repo, we'd be more than happy to revisit it if it keeps happening.

**Comment by romainmenke** [comment]
Just to clarify closing the issue has nothing to do with your issue itself.
Because the plugin has been moved we want to archive this repository.

Github locks all code, issues, and pull requests once a repository is archived.
So further discussion here would become impossible. Even informing you that it has been fixed would no longer be possible here.
